### ISSUE TITLE
AppCenterCapacitorShared 0.3.5 not installable

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [capacitor-community/appcenter-sdk-capacitor#47]
### Plugin(s)

@capacitor-community/appcenter-analytics@0.3.4
@capacitor-community/appcenter-crashes@0.7.3

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/core: 3.2.2
  @capacitor/cli: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2
```

### Platform(s)

MacOS

### Current Behavior

When `pod install` is run in a capacitor app that's depending on 
`@capacitor-community/appcenter-analytics@0.3.4` or `@capacitor-community/appcenter-crashes@0.7.3`
this error occurs 
```
[error] Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AppCenterCapacitorShared":
        In Podfile:
        CapacitorCommunityAppcenterAnalytics (from
        ../../../../../node_modules/@capacitor-community/appcenter-analytics) was resolved to 0.3.3, which depends on
        AppCenterCapacitorShared (~> 0.3.5)
        
        None of your spec sources contain a spec satisfying the dependency: AppCenterCapacitorShared (~> 0.3.5).
        
        You have either:
        * out-of-date source repos which you can update with pod repo update or with pod install --repo-update.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.
   ```

### Expected Behavior

Expected the pods to install without errors

### Additional Context

I tried reverting to `@capacitor-community/appcenter-analytics@0.3.1` and
`@capacitor-community/appcenter-crashes@0.7.0` which worked.
Those versions depend on `AppCenterCapacitorShared` version `0.3.2`, not `0.3.5`

Has `AppCenterCapacitorShared` version `0.3.5` been published yet?

**Comment by johnborges** [comment]
Did you try running `pod install --repo-update`? `0.3.5` and `1.0.0` of `AppCenterCapacitorShared` is published.

**Comment by hrafnkellbaldurs** [comment]
I tried `rm -rf ~/.cocoapods && pod setup && pod install`, haven't tried `pod install --repo-update` I think.
I'll try it when I get to it.
If this is not re-producable, then I can close this issue until I try this again
